spring:
  application:
    name: pivotal-apj-meetup-email
  cloud:
    stream:
      bindings:
        input:
          destination: email
          group: email-service

email:
  reallySend: true
  subject: Congratulations!
  body: Congratulations! You have win the game in Pivotal Event! You may present this email to the counter and receive a gift.


eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.pivotal-apj-meetup-service-registry.credentials.uri}/eureka/
  instance:
    instanceId: ${vcap.application.application_uris[0]}:${vcap.application.instance_id}
    hostname: ${vcap.application.application_uris[0]}
    non-secure-port: 80
    appname: ${vcap.application.application_name}
