spring:
  application:
    name: pivotal-apj-meetup-edge
zuul:
  routes:
    emc-forum-backend: /backend/**
    emc-forum-repository: /repository/**
    emc-forum-admin: /admin/**
    emc-forum-frontend: /**
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.emc-forum-service-registry.credentials.uri}/eureka/
  instance:
    instanceId: ${vcap.application.application_uris[0]}:${vcap.application.instance_id}
    hostname: ${vcap.application.application_uris[0]}
    non-secure-port: 80
    appname: ${vcap.application.application_name}
