spring:
  application:
    name: pivotal-apj-meetup-zipkin


eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.pivotal-apj-meetup-service-registry.credentials.uri}/eureka/
  instance:
    instanceId: ${vcap.application.application_uris[0]}:${vcap.application.instance_id}
    hostname: ${vcap.application.application_uris[0]}
    non-secure-port: 80
    appname: ${vcap.application.application_name}
