spring:
  application:
    name: pivotal-apj-meetup-edge
zuul:
  routes:
    pivotal-apj-meetup-backend: /backend/**
    pivotal-apj-meetup-repository: /repository/**
    pivotal-apj-meetup-admin: /admin/**
    pivotal-apj-meetup-frontend: /**
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.pivotal-apj-meetup-service-registry.credentials.uri}/eureka/
  instance:
    instanceId: ${vcap.application.application_uris[0]}:${vcap.application.instance_id}
    hostname: ${vcap.application.application_uris[0]}
    non-secure-port: 80
    appname: ${vcap.application.application_name}
