spring:
  application:
    name: pivotal-apj-meetup-email
  cloud:
    stream:
      bindings:
        input:
          destination: email
          group: email-service
#  mail:
#    host: ${SPRING_MAIL_HOST}
#    username: ${SPRING_MAIL_USERNAME}
#    password: ${SPRING_MAIL_PASSWORD}
#    port: ${SPRING_MAIL_PORT}
#    test-connection: ${SPRING_MAIL_TEST_CONNECTION}
#    protocol: ${SPRING_MAIL_PROTOCOL}
#    properties:
#      mail:
#        smtp.starttls.enable: ${SPRING_MAIL_SSL_ENABLE}

email:
  reallySend: true
  subject: Congratulations!
  body: Congratulations! You have win the game in Pivotal Event! You may present this email to the counter and receive a gift.


eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.pivotal-apj-meetup-service-registry.credentials.uri}/eureka/
  instance:
    instanceId: ${vcap.application.application_uris[0]}:${vcap.application.instance_id}
    hostname: ${vcap.application.application_uris[0]}
    non-secure-port: 80
    appname: ${vcap.application.application_name}
